list_of_services = {"frontend": {"has_mongo": False, 
                                  "has_memcache": False}, 
                     "profile": {"has_mongo": True, 
                                 "has_memcache": True}, 
                     "search": {"has_mongo": False, 
                                "has_memcache": False}, 
                     "geo": {"has_mongo": True, 
                             "has_memcache": False}, 
                     "rate": {"has_mongo": True, 
                              "has_memcache": True}, 
                     "review": {"has_mongo": True, 
                                "has_memcache": True}, 
                     "attractions": {"has_mongo": True, 
                                     "has_memcache": False}, 
                     "recommendation": {"has_mongo": True, 
                                        "has_memcache": False}, 
                     "user": {"has_mongo": True, 
                              "has_memcache": False}, 
                     "reservation": {"has_mongo": True, 
                                     "has_memcache": True,
                                     "memcache_alias": "reserve"}}

service_docker_options = {"tcp_rmem":{"min_val": int(4096), 
                                      "max_val": int(6291456),
                                      "step": int(1257472)}, 
                          "tcp_wmem":{"min_val": int(4096), 
                                      "max_val": int(6291456),
                                      "step": int(1257472)}, 
                          "cpu_max_ratio": {"min_val": float(0), 
                                            "max_val": float(1),
                                            "step": 0.2}}

memcache_docker_options = {"memory_limit": {"min_val": int(4096), 
                                            "max_val": int(6291456),
                                            "step": int(1257472)}, 
                           "threads": {"min_val": int(1), 
                                       "max_val": int(16),
                                       "step": 3}, 
                           "slab_growth_factor": {"min_val": float(1.1), 
                                                  "max_val": float(2.2),
                                                  "step": 0.18}}

mongo_docker_options = {"tcp_rmem":{"min_val": int(4096), 
                                      "max_val": int(6291456),
                                      "step": int(1257472)}, 
                        "tcp_wmem":{"min_val": int(4096), 
                                      "max_val": int(6291456),
                                      "step": int(1257472)}}

mongo_admin_options = {"eviction_dirty_target":{"min_val": int(10), 
                                                "max_val": int(90),
                                                "step": 20}, 
                       "eviction_dirty_trigger": {"min_val": int(1), 
                                                 "max_val": int(99),
                                                 "step": 19},
                       "wiredTigerCacheSizeGB": {"min_val": float(0.05), 
                                                 "max_val": float(0.2),
                                                 "step": 0.05}}
